### ISSUE TITLE
Correct Class Name for psr-4 please, in src/Helpers/Dumper.php

### ISSUE THREAD

**Issue by huangnie2020** [swooletw/laravel-swoole#428] opened 2020-07-25 05:27 UTC
Deprecation Notice: Class SwooleTW\Http\Helpers\VarDumper located in ./vendor/swooletw/laravel-swoole/src/Helpers/Dumper.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by alecpl** [comment] 2020-09-23 12:19
Duplicate of fixed #387.

**Comment by Arkanius** [comment] 2020-09-23 12:27
@huangnie2020 it was fixed in [2.6.68](https://github.com/swooletw/laravel-swoole/releases/tag/v2.6.68)

**Closed** 2020-10-04 08:08 UTC
Labels: fixed
