### ISSUE TITLE
Illuminate\Contracts\Container\BindingResolutionException: Target 

### ISSUE THREAD

**Issue by cielu** [swooletw/laravel-swoole#231] opened 2019-03-05 10:18 UTC
Make sure you read **Issues Guideline** and answer these questions before submitting your issue. Thanks!
(Any **non-English** issues will be closed immediately.)

1. Please provide your PHP and Swoole version. (`php -v` and `php --ri swoole`)

php  v7.2.12
swoole  v4.2.13

2. Please provide your Laravel/Lumen version.

5.7.*

3. Which release version of this package are you using?

2.6.5

4. What did you do? If possible, provide a recipe for reproducing the error.

when I open  
```
 'access_log' => env('SWOOLE_HTTP_ACCESS_LOG', false) 
```
in swoole_http.php config file , there was a

~ BindingResolutionException: Target [Illuminate\Contracts\Http\Kernel] is not instantiable. 

      // there would be bug
        if ($config->get('swoole_http.server.access_log')) {
            $this->app->make(Kernel::class)->pushMiddleware(AccessLog::class);
        }

5. What did you expect to see?

  I have been enabled the web_socket

6. What did you see instead?

**Comment by cielu** [comment] 2019-03-05 10:21
when i off the access_log ,  that would be normal

**Comment by albertcht** [comment] 2019-03-05 14:51
Unable to reproduce this error. Please test it again with a new laravel project without any other 3rd-party dependencies.

**Comment by cielu** [comment] 2019-03-06 02:25
> Unable to reproduce this error. Please test it again with a new laravel project without any other 3rd-party dependencies.

不可能啊，老铁。你开启websocket没有，把和websocket有关的都开启就会出现这个问题

**Comment by cielu** [comment] 2019-03-06 02:30
"require": {
        "php": ">=7.1.3",
        "laravel/lumen-framework": "5.7.*",
        "swooletw/laravel-swoole": "^2.6",
        "vlucas/phpdotenv": "^3.3"
    },

![image](https://user-images.githubusercontent.com/13715811/53851794-c8845380-3ffa-11e9-93fa-93a75e99751e.png)

**Comment by cielu** [comment] 2019-03-06 02:32
```
[2019-03-06 02:30:07] local.ERROR: Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Http\Kernel] is not instantiable. in /Users/ciel/Developer/chentuo/LiveChat/vendor/illuminate/container/Container.php:945
Stack trace:
#0 /Users/ciel/Developer/chentuo/LiveChat/vendor/illuminate/container/Container.php(785): Illuminate\Container\Container->notInstantiable('Illuminate\\Cont...')
#1 /Users/ciel/Developer/chentuo/LiveChat/vendor/illuminate/container/Container.php(658): Illuminate\Container\Container->build('Illuminate\\Cont...')
#2 /Users/ciel/Developer/chentuo/LiveChat/vendor/illuminate/container/Container.php(609): Illuminate\Container\Container->resolve('Illuminate\\Cont...', Array)
#3 /Users/ciel/Developer/chentuo/LiveChat/vendor/laravel/lumen-framework/src/Application.php(260): Illuminate\Container\Container->make('Illuminate\\Cont...', Array)
#4 /Users/ciel/Developer/chentuo/LiveChat/vendor/swooletw/laravel-swoole/src/HttpServiceProvider.php(91): Laravel\Lumen\Application->make('Illuminate\\Cont...')
#5 [internal function]: SwooleTW\Http\HttpServiceProvider->boot()
#6 /Users/ciel/Developer/chentuo/LiveChat/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#7 /Users/ciel/Developer/chentuo/LiveChat/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#8 /Users/ciel/Developer/chentuo/LiveChat/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#9 /Users/ciel/Developer/chentuo/LiveChat/vendor/illuminate/container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#10 /Users/ciel/Developer/chentuo/LiveChat/vendor/laravel/lumen-framework/src/Application.php(237): Illuminate\Container\Container->call(Array)
#11 /Users/ciel/Developer/chentuo/LiveChat/vendor/laravel/lumen-framework/src/Application.php(222): Laravel\Lumen\Application->bootProvider(Object(SwooleTW\Http\LumenServiceProvider))
#12 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(SwooleTW\Http\LumenServiceProvider), 'SwooleTW\\Http\\L...')
#13 /Users/ciel/Developer/chentuo/LiveChat/vendor/laravel/lumen-framework/src/Application.php(223): array_walk(Array, Object(Closure))
#14 /Users/ciel/Developer/chentuo/LiveChat/vendor/laravel/lumen-framework/src/Console/Kernel.php(113): Laravel\Lumen\Application->boot()
#15 /Users/ciel/Developer/chentuo/LiveChat/artisan(35): Laravel\Lumen\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main} {"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target [Illuminate\\Contracts\\Http\\Kernel] is not instantiable. at /Users/ciel/Developer/chentuo/LiveChat/vendor/illuminate/container/Container.php:945)
[stacktrace]
```
@albertcht

**Comment by cielu** [comment] 2019-03-06 04:51
关于客户端接收不到服务端的推送，我找到了一个地方，不知道是不是这个的原因

![image](https://user-images.githubusercontent.com/13715811/53856745-4a31ac80-400e-11e9-8303-7f943c74f651.png)

我这边就是客户端给服务端发消息，服务端能收到，但是服务端返回到客户端，客户端就收不到了

@albertcht

**Comment by cielu** [comment] 2019-03-06 05:13
```
0 {main} {"exception":"[object] (ReflectionException(code: -1): Class MainController does not exist at 

Websocket::on('test', 'MainController@test');
```
there would be another bug

**Comment by albertcht** [comment] 2019-03-06 18:02
Hi @cielu ,

The bug in `acceessLog` for lumen has been fixed in the newest release `v2.6.5.2`.

Please describe in detail or paste the partial code for your your websocket push logics. And use full namespace for your `MainController` class path.

Also, please describe one issue in an issue ticket at one time, thanks.

**Comment by cielu** [comment] 2019-03-07 01:18
@albertcht  Hey man，enable the websocket . And you will get the error

![image](https://user-images.githubusercontent.com/13715811/53925054-8837da80-40b9-11e9-8457-5ef8f624f34d.png)

![image](https://user-images.githubusercontent.com/13715811/53925073-98e85080-40b9-11e9-9267-e18c051decfa.png)

**Comment by albertcht** [comment] 2019-03-07 02:05
@cielu ,

Fixed in the release `v2.6.5.3`. Can you try it again?

**Comment by cielu** [comment] 2019-03-07 08:52
@albertcht  oh , thanks . I fixed it .

**Comment by cielu** [comment] 2019-03-07 09:33
@albertcht 

Hey , alber chen , I got another problem 

![image](https://user-images.githubusercontent.com/13715811/53946504-e509b400-40fe-11e9-82f3-1e79785cfc5d.png)

when Client to Server ,  Client can't receive Server message , but Server can receive Client message

**Comment by albertcht** [comment] 2019-03-07 14:05
Please open another issue for that with detailed description, thanks.

**Closed by albertcht** 2019-03-07 14:05 UTC
Labels: question, unable to reproduce
